export const launchData = [
    {
        title: "1M+",
        description: "monthly site visits to store.codestam.com"
    },
    {
        title: "$55M+",
        description: "in revenue generated by partners"
    },
    {
        title: "2k+",
        description: "products listed as of Octorber 2021"
    },
]